# Hyperparameter configs

# Training
model: transformer
# model: lstm
# data: "wikitext/wikitext-2-raw-v1"
data: "text/cash"
saved_data: "data/tokenized_data"
saved_dict: "data/dict_data"
save: model.pt
cpus: 1
gpus: 1
epochs: 2
wdecay: 1.2e-6
lr: 0.1

# Dictioarny
ngram: 2
unk_threshold: 0
max_dict_size: 0
fallback: True
unigram_ppl: False
weighted_loss: True
weighted_labels: True

# Model
expected_size: 0 # 100000000
embedding_size: 256
hidden_size: 256
batch_size: 1
bptt: 100
nlayers: 1
nhead: 2
dropout: 0.2

unigram_ppl: false
seed: 1111
log_interval: 200

downstream: False

