# Hyperparameter configs

# Training
model: lstm
data: "text/cash"
# data: "wikitext/wikitext-103-raw-v1"
save: model.pt
cpus: 16
gpus: 1
epochs: 20
wdecay: 1.2e-6
lr: 0.1

# Dictioarny
ngram: 1
unk_threshold: 0
max_dict_size: 0
fallback: True
unigram_ppl: True

# Model
embedding_size: 256
hidden_size: 124
batch_size: 20
bptt: 35
nlayers: 2
nhead: 2
dropout: 0.2

unigram_ppl: false
seed: 1111
log_interval: 200

# Pass wandb run id to run config for fine-tuning with flair
wandb_flair_yaml: configs/flair_base.yaml
