downstream_tasks:
- task:
    base_path: data
    dataset: conll_03
    hidden_size: 256
    lr: 0.1
    max_epochs: 150
    mini_batch_size: 32
    save: resources/taggers/conll_03-ner
    task_name: ner
model_name: transformer
saved_model: checkpoints/flair_model.pt
wandb_run_id: gerpt/2nyzwdba
