downstream_tasks:
- task:
    base_path: data
    dataset: conll_03
    hidden_size: 512
    lr: 0.1
    max_epochs: 1
    mini_batch_size: 32
    save: resources/taggers/conll_03-ner
    task_name: ner
    use: false
- task:
    base_path: null
    dataset: ud_english
    hidden_size: 256
    lr: 0.1
    max_epochs: 150
    mini_batch_size: 32
    save: resources/taggers/ud_english-upos
    task_name: upos
    use: true
- task:
    base_path: null
    dataset: glue/sst2
    hidden_size: 256
    lr: 0.1
    max_epochs: 150
    mini_batch_size: 32
    save: resources/class/sst2-sent-class
    task_name: class
    use: true
model_name: rnn
saved_model: checkpoints/flair_model.pt
seed: 1111
wandb_run_id: gerpt/d9kndxzr
